INSERT INTO DBA."ROLE" ("ROLE") 
	VALUES ('Cashier');
INSERT INTO DBA."ROLE" ("ROLE") 
	VALUES ('Director');
INSERT INTO DBA."ROLE" ("ROLE") 
	VALUES ('Admin');

INSERT INTO DBA.CATEGORY (CATEGORY) 
	VALUES ('Food');
INSERT INTO DBA.CATEGORY (CATEGORY) 
	VALUES ('Toy');
INSERT INTO DBA.CATEGORY (CATEGORY) 
	VALUES ('Tool');
INSERT INTO DBA.CATEGORY (CATEGORY) 
	VALUES ('Alcohol');

INSERT INTO DBA."STATE" ("STATE") 
	VALUES ('Pending');
INSERT INTO DBA."STATE" ("STATE") 
	VALUES ('Accepted');
INSERT INTO DBA."STATE" ("STATE") 
	VALUES ('Rejected');

INSERT INTO DBA.TRANSACTION_TYPE ("TYPE") 
	VALUES ('Sale');
INSERT INTO DBA.TRANSACTION_TYPE ("TYPE") 
	VALUES ('Rental');
INSERT INTO DBA.TRANSACTION_TYPE ("TYPE") 
	VALUES ('Return');

INSERT INTO DBA.UNIT (UNIT) 
	VALUES ('Meter');
INSERT INTO DBA.UNIT (UNIT) 
	VALUES ('Litre');
INSERT INTO DBA.UNIT (UNIT) 
	VALUES ('Kilogram');
INSERT INTO DBA.UNIT (UNIT) 
	VALUES ('Piece');
